### ISSUE TITLE
鸣潮的配置文件都需要填吗？去哪里获取

### ISSUE THREAD

**Issue by olinbrown** [tuotuooo/AutoLiver#5]
![微信截图_20240712163252](https://github.com/user-attachments/assets/7d7c8573-5036-4510-bfff-7990a2d28918)
短信验证码这些是一次性就可以？

**Comment by olinbrown** [comment]
我大概知道每个文件会获取了……但是缺一个关键的库安装不上
![Uploading 微信截图_20240712170552.png…]()

**Comment by olinbrown** [comment]
![1](https://github.com/user-attachments/assets/0f3995f0-9b67-4380-b873-1174b55f771b)
这里是需要在cfg里先填入哪几个数据

**Comment by tuotuooo** [comment]
手机号，短信验证码，库街区的ID，鸣潮的ID，战双的ID

**Comment by tuotuooo** [comment]
都填到配置文件之后，运行`dxyzm.py`：你的手机会收到一个验证码，把它填入配置文件中，再运行`phone_login.py`，再运行`main.py`即可完成mc  zs签到

**Comment by tuotuooo** [comment]
后续  只运行`main.py`即可
