### ISSUE TITLE
这两天绝区零的签到签不上了

### ISSUE THREAD

**Issue by Lawlietqwq** [tuotuooo/AutoLiver#8]
这两天绝区零的签到签不上了，带佬能不能帮忙重新抓个包update一下，本人手机没刷root权限
![image](https://github.com/user-attachments/assets/3cfc3852-2151-44d0-bbbd-1132bb4b4d6c)

**Comment by tuotuooo** [comment]
好的，估计ID有变化了。

**Comment by tuotuooo** [comment]
![image](https://github.com/user-attachments/assets/485c7dfa-f52c-4dd1-9860-74d4078824de)

**Comment by tuotuooo** [comment]
mys更新了接口地址，其他参数都没变。

**Comment by tuotuooo** [comment]
🦉已更新
